### ISSUE TITLE
Status 204

### ISSUE THREAD

**Issue by vieira-alexandre** [Ednilsonpalhares/api-controle-financeiro#1]
Man, vi seu repositório aqui do challenge 🙂

Só queria te dar um feedback de um detalhe que vi no seu Readme... o status 204 significa que a requisição foi processada com sucesso e que na resposta do servidor não tem nenhum conteúdo/corpo, o nome desse status é "No Content" por isso. Todos os status na faixa 2xx são de sucesso.

![image](https://user-images.githubusercontent.com/11696437/151730870-68a719be-b5e7-4c25-afb5-9d55d874264f.png)

Recurso não encontrado é o 404 apenas, que está na faixa 4xx que são os erros do cliente.

Bons estudos aí 🚀

**Comment by Ednilsonpalhares** [comment]
Man, obrigado pela ajuda, fiz a correção abaixo.
204  | Sem conteúdo.

**Comment by vieira-alexandre** [comment]
Show de bola.
Tamo junto.
