### ISSUE TITLE
Badge Alura Challenge

### ISSUE THREAD

**Issue by LucasdeFreitasp** [Ednilsonpalhares/api-controle-financeiro#2]
Olá, back-ender!

Primeiramente, gostaria de te parabenizar por aceitar o desafio e mergulhar de cabeça nessa segunda edição do Challenge de Back-End da Alura.
Como recordação da sua participação e reconhecimento por compartilhar seu aprendizado com a comunidade, deixamos essa badge 🏅

Abraços e te vejo nos próximos Challenges!
![bagde programacao 2](https://user-images.githubusercontent.com/79534537/155774860-fa6d3526-01b3-44f1-83af-5b78a4f3d25f.png)

**Comment by Ednilsonpalhares** [comment]
Obrigado.
